### ISSUE TITLE
Failed to start the bot due to error by genshin-impact-api

### ISSUE THREAD

**Issue by Vip3rLi0n** [epromite/HisokaBOT-Whatsapp-Bot#18]
#17 
![1](https://user-images.githubusercontent.com/21289340/112133865-17fc4300-8c07-11eb-84a2-0cb71bbf8156.png)
![2](https://user-images.githubusercontent.com/21289340/112133876-1b8fca00-8c07-11eb-8a8a-804f15ec836e.png)
![3](https://user-images.githubusercontent.com/21289340/112133885-1e8aba80-8c07-11eb-9f98-fec69ad4605e.png)

> HisokaBOT-Whatsapp-Bot@0.0.1 start C:\Users\NizzyMeow\Desktop\HisokaBOT-Whatsapp-Bot
> node index.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'genshin-impact-api'
Require stack:
- C:\Users\NizzyMeow\Desktop\HisokaBOT-Whatsapp-Bot\message\index.js
- C:\Users\NizzyMeow\Desktop\HisokaBOT-Whatsapp-Bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\NizzyMeow\Desktop\HisokaBOT-Whatsapp-Bot\message\index.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\NizzyMeow\\Desktop\\HisokaBOT-Whatsapp-Bot\\message\\index.js',
    'C:\\Users\\NizzyMeow\\Desktop\\HisokaBOT-Whatsapp-Bot\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HisokaBOT-Whatsapp-Bot@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HisokaBOT-Whatsapp-Bot@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NizzyMeow\AppData\Roaming\npm-cache\_logs\2021-03-23T10_31_38_246Z-debug.log

**Comment by ghost** [comment]
Same
